- src/main/java/com/on/server/domain/board/domain/Board.java
- src/main/java/com/on/server/domain/board/domain/repository/BoardRepository.java
- src/main/java/com/on/server/domain/board/dto/BoardDTO.java
- src/main/java/com/on/server/domain/comment/application/CommentService.java
- src/main/java/com/on/server/domain/comment/domain/Comment.java
- src/main/java/com/on/server/domain/comment/domain/repository/CommentRepository.java
- src/main/java/com/on/server/domain/comment/dto/CommentRequestDTO.java
- src/main/java/com/on/server/domain/comment/dto/CommentResponseDTO.java
- src/main/java/com/on/server/domain/comment/presentation/CommentController.java
- src/main/java/com/on/server/domain/post/application/PostService.java
- src/main/java/com/on/server/domain/post/domain/Post.java
- src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
- src/main/java/com/on/server/domain/post/dto/PostRequestDTO.java
- src/main/java/com/on/server/domain/post/dto/PostResponseDTO.java
- src/main/java/com/on/server/domain/post/presentation/PostController.java
> Comment 기능을 위한 Entity, Controller, Request/ResponseDTO를 구현했습니다.
>
>  - 기능 : 
>     - 특정 게시글의 모든 댓글 조회
>     - 게시글에 댓글 작성
>
> CommentService는 메서드 이름만 정의하였고 로직은 추후 추가하도록 하겠습니다.
> [feature] 댓글 기능 구현 - CommentController 및 DTO

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/CompanyPost.java
- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostRequestDTO.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
- src/main/java/com/on/server/domain/companyPost/presentation/CompanyPostController.java
> - CompanyPost의 Entity, DTO, Controller를 작성했습니다.
> - 기능: 동행구하기에 대한 모든 게시글 조회, 특정 게시글 조회, 새 게시글 생성, 특정 게시글 삭제
> - CompanyPostService는 CRUD 작업을 위한 메서드 구조만 정의해놨고, 실제 구현 코드는 추후 추가하도록 하겠습니다.
> - Controller의 각 엔드포인트에 스웨거 설명을 작성했습니다.
> [Feature] CompanyPost - DTO, Controller 구현

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/CompanyPost.java
- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostRequestDTO.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
- src/main/java/com/on/server/domain/companyPost/presentation/CompanyPostController.java
- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/domain/MarketPost.java
- src/main/java/com/on/server/domain/marketPost/domain/repository/MarketPostRepository.java
- src/main/java/com/on/server/domain/marketPost/dto/MarketPostRequestDTO.java
- src/main/java/com/on/server/domain/marketPost/dto/MarketPostResponseDTO.java
- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
- src/main/java/com/on/server/domain/scrap/application/ScrapService.java
- src/main/java/com/on/server/domain/scrap/domain/Scrap.java
- src/main/java/com/on/server/domain/scrap/domain/repository/ScrapRepository.java
- src/main/java/com/on/server/domain/scrap/dto/ScrapRequestDTO.java
- src/main/java/com/on/server/domain/scrap/dto/ScrapResponseDTO.java
- src/main/java/com/on/server/domain/scrap/presentation/ScrapController.java
>- 물품거래와 관련된 MarketPost와 Scrap에 대한 Entity, DTO, Controller를 작성했습니다.
>- MarketPost 기능: 물품거래에 대한 모든 거래글 조회, 특정 거래글 조회, 거래글 생성
>- Scrap 기능: 특정 물품거래글 스크랩, 스크랩한 모든 물품글 조회, 스크랩 목록에서 특정 스크랩 취소
>- MarketPostService와 ScrapService는 CRUD 작업을 위한 메서드 구조만 정의해놨고, 실제 구현 코드는 추후 추가하도록 하겠습니다.
>- Scrap 엔티티는 ERD에 추가했습니다.
> [Feature] MarketPost & Scrap DTO, Controller 구현

- .gitignore
- build.gradle
- src/main/java/com/on/server/domain/user/domain/User.java
> #6 
> user에 device token 저장하는 곳 필요해서 추가해놓았습니다
- user entity에 device token 필드 추가
- fcm 의존성 추가
- git ignore에 firebase 추가
> feat: user deviceToken 추가 및 fcm 의존성 추가

- src/main/java/com/on/server/domain/dispatchCertify/application/DispatchCertifyService.java
- src/main/java/com/on/server/domain/dispatchCertify/domain/DispatchCertify.java
- src/main/java/com/on/server/domain/dispatchCertify/domain/PermitStatus.java
- src/main/java/com/on/server/domain/dispatchCertify/domain/repository/DispatchCertifyRepository.java
- src/main/java/com/on/server/domain/dispatchCertify/dto/request/DispatchCertifyApplyRequestDto.java
- src/main/java/com/on/server/domain/dispatchCertify/dto/response/DispatchCertifyInfoResponseDto.java
- src/main/java/com/on/server/domain/dispatchCertify/persentation/DispatchCertifyController.java
- src/main/java/com/on/server/domain/user/application/UserService.java
- src/main/java/com/on/server/domain/user/domain/DispatchType.java
- src/main/java/com/on/server/domain/user/domain/User.java
- src/main/java/com/on/server/domain/user/dto/request/SignUpRequestDto.java
- src/main/java/com/on/server/domain/user/dto/response/UserInfoResponseDto.java
- src/main/java/com/on/server/domain/user/presentation/UserController.java
- src/main/java/com/on/server/global/aws/s3/uuidFile/presentation/UuidFileController.java
- src/main/java/com/on/server/global/common/ResponseCode.java
> feat: dispatch certify 관심사 구현

- src/main/java/com/on/server/domain/diary/presentation/DiaryController.java
- src/main/java/com/on/server/domain/dispatchCertify/persentation/DispatchCertifyController.java
- src/main/java/com/on/server/domain/user/application/CustomUserDetailsService.java
- src/main/java/com/on/server/domain/user/dto/response/UserInfoResponseDto.java
- src/main/java/com/on/server/domain/user/presentation/UserController.java
- src/main/java/com/on/server/global/security/SecurityService.java
---
name: UMC-ON BE PR 템플릿
about: UMC-ON BE PR 템플릿
title: "PR title"
labels: ''
assignees: ''
---
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> hotfix: auth AOP, user api 버그 핫픽스

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/domain/CompanyParticipant.java
- src/main/java/com/on/server/domain/companyParticipant/domain/CompanyParticipantStatus.java
- src/main/java/com/on/server/domain/companyParticipant/domain/repository/CompanyParticipantRepository.java
- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantRequestDTO.java
- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantResponseDTO.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
- 특정 동행구하기 게시글에 동행 신청하는 기능 구현
- 동행 신청자의 default status는 AWAIT, 동행구하기 글 작성자가 "모집완료"를 누를 시 PARTICIPANT로 status를 업데이트
> feat: 동행 신청하기 기능 구현

- src/main/java/com/on/server/domain/dispatchCertify/dto/response/DispatchCertifyInfoResponseDto.java
- src/main/java/com/on/server/domain/dispatchCertify/persentation/DispatchCertifyController.java
> fix: dispatchCertify api dto getter 추가

- src/main/java/com/on/server/global/security/config/SecurityConfig.java
---
name: UMC-ON BE PR 템플릿
about: UMC-ON BE PR 템플릿
title: "PR title"
labels: ''
assignees: ''
---
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> fix: CORS 설정 추가

- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantRequestDTO.java
---
name: UMC-ON BE PR 템플릿
about: UMC-ON BE PR 템플릿
title: "PR title"
labels: ''
assignees: ''
---
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> fix: 동행 신청하기 reqeust dto status 수정

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
- src/main/java/com/on/server/domain/chat/dto/CompanyChatResponseDto.java
- src/main/java/com/on/server/domain/chat/dto/MarketChatResponseDto.java
- src/main/java/com/on/server/domain/chat/presentation/ChatController.java
- src/main/java/com/on/server/domain/companyParticipant/domain/repository/CompanyParticipantRepository.java
- src/main/java/com/on/server/domain/companyPost/domain/CompanyPost.java
- src/main/java/com/on/server/global/common/ResponseCode.java
> #3 
- 채팅방 모집완료 시 현재모집인원 및 상태 변환 구현
- '[거래] 채팅방 목록 조회' API 구현
- '[동행] 채팅 정보 조회' API 구현
- '[거래] 채팅 정보 조회' API 구현
> feat: 채팅 API 2차 구현

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/dto/MarketPostRequestDTO.java
- marketpost requestdto에서 dealStatus 삭제
> fix: 물품거래 request dto status 수정

- src/main/java/com/on/server/domain/user/domain/User.java
- src/main/java/com/on/server/domain/user/dto/request/SignUpRequestDto.java
---
name: UMC-ON BE PR 템플릿
about: UMC-ON BE PR 템플릿
title: "PR title"
labels: ''
assignees: ''
---
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> feat: 회원가입 name 추가

- src/main/java/com/on/server/domain/dispatchCertify/dto/response/DispatchCertifyInfoResponseDto.java
> fix: dispatchCertify response Dto emial 필드 추가

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
- 물품거래글 AWAIT 상태일 때 COMPLETE로 상태를 업데이트 하도록 수정
> fix: 물품거래 상태 업데이트 로직 수정

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
> fix: 동행 신청하기 상태 업데이트 로직 수정

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
> fix: 물품거래글 DealStatus 수정

- src/main/java/com/on/server/domain/marketPost/domain/MarketPost.java
> fix: 물품거래글 DealStatus entity 재수정

- src/main/java/com/on/server/domain/comment/application/CommentService.java
- src/main/java/com/on/server/domain/comment/domain/Comment.java
- src/main/java/com/on/server/domain/comment/domain/repository/CommentRepository.java
- src/main/java/com/on/server/domain/comment/dto/CommentRequestDTO.java
- src/main/java/com/on/server/domain/comment/dto/CommentResponseDTO.java
> 댓글 및 답글 작성에서 익명 선택 시 닉네임 대신 익명 index로 출력되도록 변경
> commentResponseDTO의 userId를 id로 변경, userNickname을 nickname으로 변경
> commentResponseDTO에서 id, nickname을 writerInfo에 담아서 출력하도록 구조 변경
> feat: commentResponseDTO 변수명 및 구조 변경, 익명 인덱스 추가

- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/home/application/HomeService.java
- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/dto/FreeBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/dto/InfoBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/presentation/HomeController.java
- src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
> #35
> - 최신 정보글 조회
> - 최신 자유글 조회
> - 내 주변 동행글 조회
> [Feature] 홈 API 구현

- src/main/java/com/on/server/global/corsTest/corsTestController.java
- src/main/java/com/on/server/global/security/config/SecurityConfig.java
> feat: cors 테스트

- src/main/java/com/on/server/domain/home/application/HomeService.java
- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
> #35 
> - 홈 화면 내 주변 동행글 조회 DTO 수정
> fix: 홈화면 내 주변 동행글 조회 DTO 수정

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
> fix: 동행 신청하기 상태 업데이트 로직 삭제

- src/main/java/com/on/server/domain/marketPost/dto/MarketPostRequestDTO.java
> fix: 물품거래글 request dto에서 이미지 제외

- src/main/java/com/on/server/domain/post/application/PostService.java
- src/main/java/com/on/server/domain/post/dto/PostRequestDTO.java
- src/main/java/com/on/server/domain/post/presentation/PostController.java
> postController에서 게시물 생성 api의 ModelAttribute를 RequestPart로 변경
> feat: 정보/자유게시글 RequestPart로 수정

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
> getMarketPost, getCompanyPost 안되는 문제 수정
> fix: Post null로 조회되는 오류 수정

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/CompanyPost.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostRequestDTO.java
- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
- src/main/java/com/on/server/domain/companyPost/presentation/CompanyPostController.java
> fix: 이미지 required false로 수정하고 현재 국가 dto에 추가

- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
> fix: 이미지 required false로 수정

- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/home/application/HomeService.java
- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/dto/FreeBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/dto/InfoBoardListResponseDto.java
- 최신 정보글 dto에 postId 추가
- 최신 자유글 dto에 postId 추가
- 내 주변 동행글 dto에 postId 추가
- 동행글 repository 수정
> feat: 홈화면 게시글 id 추가

- src/main/java/com/on/server/domain/chat/application/ChatService.java
> 생성된 채팅방에 메시지 없을 경우 null 반환하도록 수정
> feat: 채팅 메시지 없을 경우 null 반환

- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
> fix: 국가 필터링 수정

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/domain/repository/MarketPostRepository.java
- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
- 내 주변 (국가 기준) 물품거래글 await 상태인 최신 3개 조회하기 api 추가
- 물품 거래글 내가 쓴 글은 조회에서 제외하도록 수정
> feat: 주변 물품거래글 api 추가

- src/main/java/com/on/server/domain/post/application/PostService.java
- src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
> 게시물 작성자의 국가기준으로 게시물이 필터링되도록 변경
> feat: 국가필터링 변경

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/domain/repository/MarketPostRepository.java
> fix: 물품거래글 조회 최신순 정렬로 수정

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
> fix: 동행구하기글 조회 최신순 정렬로 수정

- src/main/java/com/on/server/domain/marketPost/domain/repository/MarketPostRepository.java
> fix: 검색 쿼리 수정

- src/main/java/com/on/server/domain/home/application/HomeService.java
- 홈 화면 자유, 정보 글 시간 포맷 수정
- 홈 화면 자유, 정보 글 댓글 수 수정
> feat: 홈 화면 시간포맷 및 댓글 수 수정

- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/home/application/HomeService.java
- 홈 화면 내 주변 동행구하기 이미지 null 값 예외 처리 추가
> fix: 홈화면 내주변 동행구하기 수정

- src/main/java/com/on/server/domain/scrap/application/ScrapService.java
- marketpost와 매핑시 createdAt 추가
> fix: 스크랩 조회시 작성시간 매핑

- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
- 내주변동행 dto travelPlace -> travelArea 로 변경
> fix: 내주변동행 dto travelArea 수정

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
- src/main/java/com/on/server/domain/companyPost/presentation/CompanyPostController.java
-  동행구하기 필터링에서 지역 제외 국가만 필터링 되도록 수정
> fix: 동행구하기 국가 필터 수정

- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
> feat: 물품거래글 필터링에 거래상태 추가

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
> `receiverId`, `userId` 가 일치하는 채팅방 있으면 그 채팅방의 `roomId` 응답하도록 수정
> feat: 기존에 존재하는 채팅방 응답 로직 추가

- src/main/java/com/on/server/domain/home/application/HomeService.java
> fix: info/free 게시글 comment 수정

- src/main/java/com/on/server/domain/post/domain/Post.java
> fix : post엔티티 content 길이 지정

- src/main/java/com/on/server/global/security/config/SecurityConfig.java
> fix: 도메인 주소 추가

- src/main/java/com/on/server/global/security/config/SecurityConfig.java
> 프론트엔드 도메인 주소 변경 (CORS 에러 해결)
> fix: 프론트 도메인 변경

- .github/workflows/gradle.yml
- src/main/java/com/on/server/global/security/config/SecurityConfig.java
> - 프론트엔드 도메인 주소 추가
> - gradle.yml 파일 artifact 버전 v3로 변경
> fix: 프론트 도메인 추가

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantRequestDTO.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
- UserDetails에서 User 객체를 가져오도록 수정
> [Refactor] 동행신청하기 API 리팩토링

- src/main/java/com/on/server/domain/home/application/HomeService.java
- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
- src/main/java/com/on/server/domain/home/presentation/HomeController.java
- src/main/java/com/on/server/global/util/FormatTimeUtil.java
> #78 
- `HomeService` 의 `getCompanyBoardDto` Dto로 옮기기
- 날짜 포맷팅 함수 `global/util` 로 분리
- 응답 `ResponseEntity` 로 통일
> [Refactor] 홈 API 리팩토링

- src/main/java/com/on/server/domain/diary/application/DiaryService.java
- src/main/java/com/on/server/domain/diary/domain/Diary.java
- src/main/java/com/on/server/domain/diary/dto/DiaryDto.java
- src/main/java/com/on/server/domain/diary/presentation/DiaryController.java
> #80
- 응답 `ResponseEntity` 로 통일
- 도메인 `cloumn` 추가
- 도메인 `id`, `writtenDate` 삭제
- `Annotation` 수정
> [Refactor] 일기 API 리팩토링

- src/main/java/com/on/server/domain/alarm/application/AlertService.java
- src/main/java/com/on/server/domain/alarm/domain/AlertType.java
- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/presentation/ChatController.java
- src/main/java/com/on/server/domain/comment/application/CommentService.java
- src/main/java/com/on/server/domain/comment/presentation/CommentController.java
- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
- src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
- src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
- src/main/java/com/on/server/global/common/ResponseCode.java
- 채팅 알림 추가
- 기존 알림 title, body 내용 수정
- 예외 처리 수정
> fix: 채팅 알림 추가 및 기존 알림 수정

- src/main/java/com/on/server/domain/alarm/application/AlertService.java
- src/main/java/com/on/server/domain/alarm/dto/AlertListResponseDto.java
- 알림 리스트 조회 시 알림 id, 알림 읽음 상태 추가
> feat: 알림 리스트 알림 id 및 읽음 상태 추가

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
- src/main/java/com/on/server/domain/chat/dto/response/ChatListDto.java
- src/main/java/com/on/server/domain/chat/dto/response/CompanyChatDto.java
- 채팅 내용 조회 API → `채팅방 생성자 id` & `상대방 id` 응답하도록 DTO 수정
- 채팅방 목록 조회 API → 채팅 내용 없을 경우 채팅방 생성 시간 리턴
- 채팅 요청 API → existingRoom 검증 로직 변경
> [Feature & Fix] 채팅 API 수정

- src/main/java/com/on/server/domain/post/application/PostService.java
- src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
- src/main/java/com/on/server/domain/post/presentation/PostController.java
> 정보/자유게시물의 국가 필터링 기능으로 조회할 때 paging 추가
> Feature: 정보/자유게시물의 국가 필터링 기능에 paging 추가

- src/main/java/com/on/server/domain/comment/application/CommentService.java
- src/main/java/com/on/server/domain/comment/domain/repository/CommentRepository.java
댓글을 기준으로 페이징 처리하고, 각 댓글에 연결된 답글이 함께 조회되도록 수정
> Fix: 댓글과 답글 paging 조회 수정

- src/main/java/com/on/server/domain/alarm/domain/AlertType.java
- src/main/java/com/on/server/domain/chat/application/ChatService.java
- 채팅 알림 type CHAT에서 MARKET_CHAT, COMPANY_CHAT 으로 구분
> feat: 채팅 알림 type 마켓, 동행 구분

- src/main/java/com/on/server/domain/user/application/UserService.java
User Service Layer `@Transcational` 안 붙은 method 수정
> fix: User Service Layer @Transcational 안 붙은 method 수정

- src/main/java/com/on/server/domain/user/presentation/UserController.java
- src/main/java/com/on/server/global/security/config/SecurityConfig.java
- id/pw찾기 api security config 허용
> fix: id/pw찾기 api security config 허용

- src/main/java/com/on/server/domain/diary/application/DiaryService.java
- src/main/java/com/on/server/domain/diary/domain/Diary.java
- src/main/java/com/on/server/domain/diary/dto/DiaryDto.java
- src/main/java/com/on/server/domain/diary/dto/DiaryRequestDto.java
> fix: 일기 작성 시 선택한 날짜로 저장하도록 수정

- src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
- src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
- src/main/java/com/on/server/domain/user/application/UserService.java
- src/main/java/com/on/server/domain/user/domain/User.java
- src/main/java/com/on/server/domain/user/domain/repository/UserRepository.java
- src/main/java/com/on/server/domain/user/dto/request/FindIDRequestDto.java
- src/main/java/com/on/server/domain/user/dto/request/SendPWAuthNumRequestDto.java
- src/main/java/com/on/server/domain/user/dto/request/SignUpRequestDto.java
- 기존 User entity의 age 칼럼을 birth로 변경했습니다.
> fix: 사용자 나이 대신 생년월일로 수정

- src/main/java/com/on/server/global/common/GlobalExceptionHandler.java
- src/main/java/com/on/server/global/common/ResponseType.java
- 로그인시, or BadCredential Exceptin 발생 시 401 에러 발생으로 수정
- BadRequest Exception 시 400에러로 수정
> fix: Exception handler 수정

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/companyParticipant/domain/repository/CompanyParticipantRepository.java
- 동행 모집 오류 수정 (같은 사람끼리 채팅방 생성된 경우)
> fix: 동행 모집 오류 수정

- src/main/java/com/on/server/domain/chat/application/ChatService.java
- src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
> [Fix] 채팅방 목록 조회 쿼리 수정

- src/main/java/com/on/server/ServerApplication.java
> feat: swagger base url fix

- src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
- src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
> fix: 동행글 추천에서 현재 글 제외하도록 수정

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/domain/repository/CompanyParticipantRepository.java
- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantResponseDTO.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
> feat: 특정 사용자가 특정 동행글에 대한 동행 신청 상태 조회 api 구현

- src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
- src/main/java/com/on/server/domain/companyParticipant/domain/repository/CompanyParticipantRepository.java
- src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantResponseDTO.java
- src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
> fix: 채팅방 ID를 받도록 동행 신청 상태 조회 로직 수정
